Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-AuditPolicyResult {param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation)New-CISResult -ControlID $ControlID -Category 'Audit Policy' -SubCategory 'Advanced Audit Policy' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - Advanced Audit Policy Configuration'}
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    $auditpol=Join-Path $env:SystemRoot 'System32\auditpol.exe';$categories=@('Account Logon','Logon','Account Management','Policy Change','Privilege Use','Object Access','DS Access','Detailed Tracking','System');$id=0
    foreach($category in $categories){$id++;if(-not(Test-Path -LiteralPath $auditpol -PathType Leaf)){New-AuditPolicyResult -ControlID ('AUD-{0:d3}' -f $id) -Title $category -Expected 'Audit category configuration is available.' -Actual 'Unavailable' -Status WARNING -Severity Medium -Evidence 'auditpol.exe is unavailable.' -Remediation 'Verify the Windows audit policy management tool is available.';continue};try{$lines=@(& $auditpol /get "/category:$category" /r 2>$null)}catch{$lines=@()};if($LASTEXITCODE -ne 0 -or $lines.Count -eq 0){New-AuditPolicyResult -ControlID ('AUD-{0:d3}' -f $id) -Title $category -Expected 'Audit subcategories are configured and reviewed.' -Actual 'Unavailable' -Status WARNING -Severity Medium -Evidence ("auditpol query failed with exit code {0}." -f $LASTEXITCODE) -Remediation ('Configure and review advanced audit policy for the {0} category.' -f $category);continue};$data=@($lines|Select-Object -Skip 1);New-AuditPolicyResult -ControlID ('AUD-{0:d3}' -f $id) -Title $category -Expected 'Audit subcategories are configured and reviewed.' -Actual ($data -join ' | ') -Status $(if($data.Count){'PASS'}else{'WARNING'}) -Severity Medium -Evidence ('auditpol returned {0} policy row(s) for {1}.' -f $data.Count,$category) -Remediation ('Review success and failure auditing requirements for every {0} subcategory.' -f $category)}
}
Export-ModuleMember -Function Invoke-Audit
