Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-BitLockerResult { param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation) New-CISResult -ControlID $ControlID -Category 'BitLocker' -SubCategory 'Volume Encryption' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - BitLocker Drive Encryption' }
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    try { $volumes=@(Get-BitLockerVolume -ErrorAction Stop) } catch { foreach($item in @(@('BL-001','BitLocker Enabled'),@('BL-002','Encryption Method'),@('BL-003','Recovery Key Present'))){New-BitLockerResult -ControlID $item[0] -Title $item[1] -Expected 'BitLocker information is available.' -Actual 'Unavailable' -Status WARNING -Severity High -Evidence $_.Exception.Message -Remediation 'Verify BitLocker is installed and run on a supported Windows edition.'};$volumes=@() }
    if($volumes.Count -gt 0){$protected=@($volumes|Where-Object ProtectionStatus -eq 'On'); New-BitLockerResult -ControlID 'BL-001' -Title 'BitLocker Enabled' -Expected 'Protection on for every fixed operating-system or data volume' -Actual (@($volumes|ForEach-Object{'{0}={1}' -f $_.MountPoint,$_.ProtectionStatus}) -join '; ') -Status $(if($protected.Count -eq $volumes.Count){'PASS'}else{'FAIL'}) -Severity High -Evidence ('Protected volumes: {0} of {1}.' -f $protected.Count,$volumes.Count) -Remediation 'Enable BitLocker protection for unprotected fixed volumes.'
        $methods=@($volumes|ForEach-Object{'{0}={1}' -f $_.MountPoint,$_.EncryptionMethod});New-BitLockerResult -ControlID 'BL-002' -Title 'Encryption Method' -Expected 'A supported strong encryption method is configured' -Actual ($methods -join '; ') -Status $(if(@($volumes|Where-Object{$_.EncryptionMethod -match 'None|Unknown'}).Count -eq 0){'PASS'}else{'FAIL'}) -Severity High -Evidence ($methods -join '; ') -Remediation 'Encrypt volumes using a supported AES-based BitLocker encryption method.'
        $withoutRecovery=@($volumes|Where-Object{@($_.KeyProtector|Where-Object KeyProtectorType -eq 'RecoveryPassword').Count -eq 0});New-BitLockerResult -ControlID 'BL-003' -Title 'Recovery Key Present' -Expected 'A recovery-password protector exists for every encrypted volume' -Actual $(if($withoutRecovery.Count){(@($withoutRecovery|ForEach-Object MountPoint)-join '; ')}else{'Recovery protector present on all volumes'}) -Status $(if($withoutRecovery.Count){'FAIL'}else{'PASS'}) -Severity Critical -Evidence ('Volumes without a RecoveryPassword protector: {0}.' -f $withoutRecovery.Count) -Remediation 'Add and securely escrow a BitLocker recovery-password protector for every encrypted volume.' }
    try{$tpm=Get-Tpm -ErrorAction Stop;$props=@(@('BL-004','TPM Available','TpmPresent'),@('BL-005','TPM Ready','TpmReady'),@('BL-006','TPM Activated','TpmActivated'),@('BL-007','TPM Ownership','TpmOwned'));foreach($item in $props){$value=$tpm.($item[2]);New-BitLockerResult -ControlID $item[0] -Title $item[1] -Expected 'True' -Actual ([string]$value) -Status $(if($value){'PASS'}else{'FAIL'}) -Severity High -Evidence ('{0}: {1}.' -f $item[2],$value) -Remediation ('Initialize, activate, and provision the TPM as required for BitLocker.')}}catch{foreach($item in @(@('BL-004','TPM Available'),@('BL-005','TPM Ready'),@('BL-006','TPM Activated'),@('BL-007','TPM Ownership'))){New-BitLockerResult -ControlID $item[0] -Title $item[1] -Expected 'TPM status is available.' -Actual 'Unavailable' -Status WARNING -Severity Medium -Evidence $_.Exception.Message -Remediation 'Verify that a compatible TPM is available and initialized.'}}
}
Export-ModuleMember -Function Invoke-Audit
