Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'SecurityAuditUtilities.psm1') -Force -ErrorAction Stop
function Get-MdeValue { param([object]$Object,[string]$Name) if($null -ne $Object -and $null -ne $Object.PSObject.Properties[$Name]){$Object.$Name}else{$null} }
function Invoke-Audit {[CmdletBinding()][OutputType([pscustomobject])]param();$svc=Get-Service Sense -ErrorAction SilentlyContinue;if($null -eq $svc){foreach($name in @('Sensor Running','Onboarding Status','Tamper Protection','EDR Block Mode','Cloud Protection','Health Status','Machine ID','Tenant ID','Signature Version','Platform Version','Engine Version')){New-CISAuditFinding 'MDE-001' 'Defender for Endpoint' 'Microsoft Defender for Endpoint' $name 'MDE is installed.' 'Not installed' 'NOT APPLICABLE' Informational 'Microsoft Defender for Endpoint Sensor service (Sense) was not found.' 'Install and onboard Microsoft Defender for Endpoint if required.'};return};try{$s=Get-MpComputerStatus -ErrorAction Stop}catch{$s=$null};$items=@(@('MDE-001','Sensor Running',$svc.Status),@('MDE-002','Onboarding Status',(Get-CISRegistryValue 'HKLM:\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status' 'OnboardingState')),@('MDE-003','Tamper Protection',(Get-MdeValue $s 'IsTamperProtected')),@('MDE-004','EDR Block Mode',(Get-CISRegistryValue 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection' 'ForceDefenderPassiveMode')),@('MDE-005','Cloud Protection',(Get-MdeValue $s 'AMServiceEnabled')),@('MDE-006','Health Status',(Get-MdeValue $s 'AntivirusEnabled')),@('MDE-007','Machine ID',(Get-CISRegistryValue 'HKLM:\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status' 'MachineId')),@('MDE-008','Tenant ID',(Get-CISRegistryValue 'HKLM:\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status' 'TenantId')),@('MDE-009','Signature Version',(Get-MdeValue $s 'AntivirusSignatureVersion')),@('MDE-010','Platform Version',(Get-MdeValue $s 'AMProductVersion')),@('MDE-011','Engine Version',(Get-MdeValue $s 'AMEngineVersion')));foreach($i in $items){New-CISAuditFinding $i[0] 'Defender for Endpoint' 'Microsoft Defender for Endpoint' $i[1] 'Configured and healthy.' ([string]$i[2]) $(if($null -eq $i[2]){'WARNING'}else{'PASS'}) Medium "$($i[1])=$($i[2])" 'Review Defender for Endpoint onboarding and health configuration.'}}
Export-ModuleMember -Function Invoke-Audit
<#
.SYNOPSIS
    Provides legacy Microsoft Defender for Endpoint health checks.
.DESCRIPTION
    Retained as a non-CIS advisory module and excluded from the v2 CIS
    compliance score.
#>
