Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-DefenderResult { param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation) New-CISResult -ControlID $ControlID -Category 'Defender' -SubCategory 'Microsoft Defender Antivirus' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'Microsoft Defender Antivirus security baseline' }
function Get-DefenderValue { param([object]$Object,[string]$Name) if($null -ne $Object -and $null -ne $Object.PSObject.Properties[$Name]){return $Object.$Name};return $null }
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    try{$preference=Get-MpPreference -ErrorAction Stop;$status=Get-MpComputerStatus -ErrorAction Stop}catch{foreach($item in @(@('DEF-001','Real Time Protection'),@('DEF-002','Cloud Protection'),@('DEF-003','Behavior Monitoring'),@('DEF-004','Tamper Protection'),@('DEF-005','Network Protection'),@('DEF-006','PUA Protection'),@('DEF-007','Controlled Folder Access'),@('DEF-008','ASR Rules'),@('DEF-009','Signature Version'),@('DEF-010','Last Signature Update'))){New-DefenderResult -ControlID $item[0] -Title $item[1] -Expected 'Microsoft Defender status is available.' -Actual 'Unavailable' -Status WARNING -Severity High -Evidence $_.Exception.Message -Remediation 'Verify Microsoft Defender Antivirus is installed, enabled, and accessible.'};return}
    $rt=Get-DefenderValue $status 'RealTimeProtectionEnabled';New-DefenderResult -ControlID 'DEF-001' -Title 'Real Time Protection' -Expected 'Enabled' -Actual ([string]$rt) -Status $(if($rt){'PASS'}else{'FAIL'}) -Severity Critical -Evidence ('RealTimeProtectionEnabled: {0}.' -f $rt) -Remediation 'Enable Microsoft Defender real-time protection.'
    $maps=Get-DefenderValue $preference 'MAPSReporting';$blockFirst=Get-DefenderValue $preference 'DisableBlockAtFirstSeen';New-DefenderResult -ControlID 'DEF-002' -Title 'Cloud Protection' -Expected 'MAPS reporting enabled and block at first sight enabled' -Actual ('MAPSReporting={0}; DisableBlockAtFirstSeen={1}' -f $maps,$blockFirst) -Status $(if($maps -and -not $blockFirst){'PASS'}else{'FAIL'}) -Severity High -Evidence ('MAPSReporting: {0}; DisableBlockAtFirstSeen: {1}.' -f $maps,$blockFirst) -Remediation 'Enable cloud-delivered protection and block at first sight.'
    $behavior=Get-DefenderValue $status 'BehaviorMonitorEnabled';New-DefenderResult -ControlID 'DEF-003' -Title 'Behavior Monitoring' -Expected 'Enabled' -Actual ([string]$behavior) -Status $(if($behavior){'PASS'}else{'FAIL'}) -Severity High -Evidence ('BehaviorMonitorEnabled: {0}.' -f $behavior) -Remediation 'Enable Microsoft Defender behavior monitoring.'
    $tamper=Get-DefenderValue $status 'IsTamperProtected';New-DefenderResult -ControlID 'DEF-004' -Title 'Tamper Protection' -Expected 'Enabled' -Actual $(if($null -eq $tamper){'Unavailable'}else{[string]$tamper}) -Status $(if($null -eq $tamper){'WARNING'}elseif($tamper){'PASS'}else{'FAIL'}) -Severity High -Evidence ('IsTamperProtected: {0}.' -f $(if($null -eq $tamper){'<unavailable>'}else{$tamper})) -Remediation 'Enable Defender Tamper Protection through Windows Security or managed security policy.'
    $network=Get-DefenderValue $preference 'EnableNetworkProtection';New-DefenderResult -ControlID 'DEF-005' -Title 'Network Protection' -Expected 'Enabled (block mode)' -Actual ([string]$network) -Status $(if($network -eq 1){'PASS'}elseif($null -eq $network){'WARNING'}else{'FAIL'}) -Severity High -Evidence ('EnableNetworkProtection: {0}.' -f $network) -Remediation 'Enable Microsoft Defender Network Protection in block mode.'
    $pua=Get-DefenderValue $preference 'PUAProtection';New-DefenderResult -ControlID 'DEF-006' -Title 'PUA Protection' -Expected 'Enabled (block mode)' -Actual ([string]$pua) -Status $(if($pua -eq 1){'PASS'}elseif($null -eq $pua){'WARNING'}else{'FAIL'}) -Severity Medium -Evidence ('PUAProtection: {0}.' -f $pua) -Remediation 'Enable potentially unwanted application protection in block mode.'
    $cfa=Get-DefenderValue $preference 'EnableControlledFolderAccess';New-DefenderResult -ControlID 'DEF-007' -Title 'Controlled Folder Access' -Expected 'Enabled (block mode)' -Actual ([string]$cfa) -Status $(if($cfa -eq 1){'PASS'}elseif($null -eq $cfa){'WARNING'}else{'FAIL'}) -Severity Medium -Evidence ('EnableControlledFolderAccess: {0}.' -f $cfa) -Remediation 'Enable Controlled Folder Access in block mode.'
    $asrIds=@(Get-DefenderValue $preference 'AttackSurfaceReductionRules_Ids');$asrActions=@(Get-DefenderValue $preference 'AttackSurfaceReductionRules_Actions');New-DefenderResult -ControlID 'DEF-008' -Title 'ASR Rules' -Expected 'At least one Attack Surface Reduction rule is configured in block or warn mode' -Actual ('Rule count: {0}; actions: {1}' -f $asrIds.Count,($asrActions -join ', ')) -Status $(if($asrIds.Count -gt 0){'PASS'}else{'FAIL'}) -Severity High -Evidence ('ASR rule IDs: {0}.' -f ($asrIds -join '; ')) -Remediation 'Configure appropriate Attack Surface Reduction rules through Microsoft Defender policy.'
    $version=Get-DefenderValue $status 'AntivirusSignatureVersion';New-DefenderResult -ControlID 'DEF-009' -Title 'Signature Version' -Expected 'A current antivirus signature version is installed' -Actual ([string]$version) -Status $(if([string]::IsNullOrWhiteSpace([string]$version)){'FAIL'}else{'PASS'}) -Severity High -Evidence ('AntivirusSignatureVersion: {0}.' -f $version) -Remediation 'Update Microsoft Defender Antivirus security intelligence.'
    $last=Get-DefenderValue $status 'AntivirusSignatureLastUpdated';$lastDate=$null;try{$lastDate=[datetime]$last}catch{};New-DefenderResult -ControlID 'DEF-010' -Title 'Last Signature Update' -Expected 'Updated within the last 7 days' -Actual $(if($lastDate){$lastDate.ToString('o')}else{'Unavailable'}) -Status $(if($null -eq $lastDate){'WARNING'}elseif($lastDate -ge (Get-Date).AddDays(-7)){'PASS'}else{'FAIL'}) -Severity High -Evidence ('AntivirusSignatureLastUpdated: {0}.' -f $last) -Remediation 'Update Microsoft Defender Antivirus security intelligence and verify scheduled updates.'
}
Export-ModuleMember -Function Invoke-Audit
