Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-SecurityPolicyResult {param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation)New-CISResult -ControlID $ControlID -Category 'Security Policy' -SubCategory 'Local Security Options' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - Local Policies'}
function Get-PolicyRegistryValue {param([string]$Path,[string]$Name)try{return Get-ItemPropertyValue -LiteralPath $Path -Name $Name -ErrorAction Stop}catch{return $null}}
function Get-RemoteShutdownPrivilege { $secedit=Join-Path $env:SystemRoot 'System32\secedit.exe';if(-not(Test-Path $secedit)){throw 'secedit.exe is unavailable.'};$path=Join-Path ([IO.Path]::GetTempPath()) ('CISUserRights_{0}.inf' -f [guid]::NewGuid().ToString('N'));try{& $secedit /export /cfg $path /areas USER_RIGHTS 2>$null|Out-Null;if($LASTEXITCODE -ne 0){throw "secedit export failed with exit code $LASTEXITCODE."};$line=Get-Content -LiteralPath $path -ErrorAction Stop|Where-Object{$_ -match '^SeRemoteShutdownPrivilege\s*='}|Select-Object -First 1;if($null -eq $line){throw 'SeRemoteShutdownPrivilege was not present in the exported policy.'};return (($line -split '=',2)[1]).Trim()}finally{if(Test-Path $path){Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue}}}
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    $lsa='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa';$system='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    $lm=Get-PolicyRegistryValue $lsa 'LmCompatibilityLevel';New-SecurityPolicyResult -ControlID 'SEC-001' -Title 'LAN Manager Authentication Level' -Expected 'Send NTLMv2 response only; refuse LM and NTLM (value 5 or higher)' -Actual ([string]$lm) -Status $(if($null -eq $lm){'WARNING'}elseif([int]$lm -ge 5){'PASS'}else{'FAIL'}) -Severity High -Evidence ('LmCompatibilityLevel: {0}.' -f $lm) -Remediation 'Set Network security: LAN Manager authentication level to value 5.'
    $noLmHash=Get-PolicyRegistryValue $lsa 'NoLMHash';$restrictNtlm=Get-PolicyRegistryValue $lsa 'RestrictSendingNTLMTraffic';New-SecurityPolicyResult -ControlID 'SEC-002' -Title 'NTLM Settings' -Expected 'LM hashes disabled and outgoing NTLM restricted' -Actual ('NoLMHash={0}; RestrictSendingNTLMTraffic={1}' -f $noLmHash,$restrictNtlm) -Status $(if($noLmHash -eq 1 -and $restrictNtlm -ge 1){'PASS'}elseif($null -eq $noLmHash -or $null -eq $restrictNtlm){'WARNING'}else{'FAIL'}) -Severity High -Evidence ('NoLMHash: {0}; RestrictSendingNTLMTraffic: {1}.' -f $noLmHash,$restrictNtlm) -Remediation 'Do not store LM hashes and restrict outgoing NTLM traffic according to compatibility requirements.'
    $uac=Get-PolicyRegistryValue $system 'EnableLUA';$consent=Get-PolicyRegistryValue $system 'ConsentPromptBehaviorAdmin';$secureDesktop=Get-PolicyRegistryValue $system 'PromptOnSecureDesktop';New-SecurityPolicyResult -ControlID 'SEC-003' -Title 'UAC' -Expected 'UAC enabled with secure desktop consent prompts' -Actual ('EnableLUA={0}; ConsentPromptBehaviorAdmin={1}; PromptOnSecureDesktop={2}' -f $uac,$consent,$secureDesktop) -Status $(if($uac -eq 1 -and $secureDesktop -eq 1 -and $consent -ge 2){'PASS'}elseif($null -eq $uac){'WARNING'}else{'FAIL'}) -Severity High -Evidence ('EnableLUA: {0}; ConsentPromptBehaviorAdmin: {1}; PromptOnSecureDesktop: {2}.' -f $uac,$consent,$secureDesktop) -Remediation 'Enable UAC and configure administrator consent prompts on the secure desktop.'
    $cad=Get-PolicyRegistryValue $system 'DisableCAD';New-SecurityPolicyResult -ControlID 'SEC-004' -Title 'Ctrl+Alt+Delete' -Expected 'Secure attention sequence required (DisableCAD = 0)' -Actual ([string]$cad) -Status $(if($cad -eq 0){'PASS'}elseif($null -eq $cad){'WARNING'}else{'FAIL'}) -Severity Medium -Evidence ('DisableCAD: {0}.' -f $cad) -Remediation 'Require Ctrl+Alt+Delete before interactive sign-in.'
    $restrictSam=Get-PolicyRegistryValue $lsa 'RestrictAnonymousSAM';$anonymousEveryone=Get-PolicyRegistryValue $lsa 'EveryoneIncludesAnonymous';New-SecurityPolicyResult -ControlID 'SEC-005' -Title 'Anonymous SID Enumeration' -Expected 'Anonymous SAM enumeration restricted and anonymous users excluded from Everyone' -Actual ('RestrictAnonymousSAM={0}; EveryoneIncludesAnonymous={1}' -f $restrictSam,$anonymousEveryone) -Status $(if($restrictSam -eq 1 -and $anonymousEveryone -eq 0){'PASS'}elseif($null -eq $restrictSam){'WARNING'}else{'FAIL'}) -Severity High -Evidence ('RestrictAnonymousSAM: {0}; EveryoneIncludesAnonymous: {1}.' -f $restrictSam,$anonymousEveryone) -Remediation 'Restrict anonymous enumeration of SAM accounts and shares, and exclude anonymous users from Everyone.'
    $restrictAnonymous=Get-PolicyRegistryValue $lsa 'RestrictAnonymous';New-SecurityPolicyResult -ControlID 'SEC-006' -Title 'Network Access' -Expected 'Anonymous network access restricted (RestrictAnonymous = 1 or higher)' -Actual ([string]$restrictAnonymous) -Status $(if($null -eq $restrictAnonymous){'WARNING'}elseif([int]$restrictAnonymous -ge 1){'PASS'}else{'FAIL'}) -Severity High -Evidence ('RestrictAnonymous: {0}.' -f $restrictAnonymous) -Remediation 'Restrict anonymous access to named pipes and shares.'
    try{$remoteRights=Get-RemoteShutdownPrivilege;New-SecurityPolicyResult -ControlID 'SEC-007' -Title 'Remote Shutdown' -Expected 'SeRemoteShutdownPrivilege limited to approved administrators' -Actual $remoteRights -Status $(if($remoteRights -match 'S-1-5-32-544'){ 'PASS' }else{'FAIL'}) -Severity High -Evidence ('SeRemoteShutdownPrivilege: {0}.' -f $remoteRights) -Remediation 'Limit Force shutdown from a remote system to Administrators or other documented approved identities.'}catch{New-SecurityPolicyResult -ControlID 'SEC-007' -Title 'Remote Shutdown' -Expected 'Remote shutdown right is available for review.' -Actual 'Unavailable' -Status WARNING -Severity High -Evidence $_.Exception.Message -Remediation 'Review SeRemoteShutdownPrivilege in Local Security Policy.'}
    $lastUser=Get-PolicyRegistryValue $system 'DontDisplayLastUserName';New-SecurityPolicyResult -ControlID 'SEC-008' -Title 'Interactive Logon' -Expected 'Last signed-in user name is not displayed' -Actual ([string]$lastUser) -Status $(if($lastUser -eq 1){'PASS'}elseif($null -eq $lastUser){'WARNING'}else{'FAIL'}) -Severity Medium -Evidence ('DontDisplayLastUserName: {0}.' -f $lastUser) -Remediation 'Enable Interactive logon: Do not display last signed-in.'
    $cached=Get-PolicyRegistryValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' 'CachedLogonsCount';$cachedNumber=0;$isNumber=[int]::TryParse([string]$cached,[ref]$cachedNumber);New-SecurityPolicyResult -ControlID 'SEC-009' -Title 'Cached Logons' -Expected '4 or fewer cached interactive logons' -Actual ([string]$cached) -Status $(if(-not $isNumber){'WARNING'}elseif($cachedNumber -le 4){'PASS'}else{'FAIL'}) -Severity Medium -Evidence ('CachedLogonsCount: {0}.' -f $cached) -Remediation 'Set Interactive logon: Number of previous logons to cache to 4 or fewer.'
}
Export-ModuleMember -Function Invoke-Audit
<#
.SYNOPSIS
    Provides legacy local security-policy checks.
.DESCRIPTION
    Retained for compatibility with framework v1. The v2 benchmark engine uses
    its generic SecurityPolicy and UserRight providers.
#>
