Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-ServiceResult {param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation)New-CISResult -ControlID $ControlID -Category 'Services' -SubCategory 'Service Hardening' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - System Services'}
function Test-ServiceDisabled {param([string]$ControlID,[string]$Title,[string[]]$Names,[string]$Severity='Medium')$found=@();foreach($name in $Names){try{$service=Get-CimInstance Win32_Service -Filter "Name='$name'" -ErrorAction Stop;if($null -ne $service){$found+=$service}}catch{}};if($found.Count -eq 0){New-ServiceResult -ControlID $ControlID -Title $Title -Expected 'Disabled when not required' -Actual 'Not installed' -Status 'NOT APPLICABLE' -Severity $Severity -Evidence 'No matching service was installed.' -Remediation 'No action required unless the service is installed later.';return};$actual=@($found|ForEach-Object{'{0}: State={1}, StartMode={2}' -f $_.Name,$_.State,$_.StartMode});$unsafe=@($found|Where-Object{$_.State -eq 'Running' -or $_.StartMode -ne 'Disabled'});New-ServiceResult -ControlID $ControlID -Title $Title -Expected 'Stopped and Disabled unless a documented exception exists' -Actual ($actual -join '; ') -Status $(if($unsafe.Count){'FAIL'}else{'PASS'}) -Severity $Severity -Evidence ($actual -join '; ') -Remediation ('Stop and disable {0} when it is not required, or document the business exception.' -f $Title)}
function Invoke-Audit {[CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param();$checks=@(@('SVC-001','Remote Registry',@('RemoteRegistry'),'High'),@('SVC-002','Telnet',@('TlntSvr'),'High'),@('SVC-003','SNMP',@('SNMP'),'Medium'),@('SVC-004','FTP',@('FTPSVC','MSFTPSVC'),'High'),@('SVC-005','WebClient',@('WebClient'),'Medium'),@('SVC-006','Bluetooth',@('bthserv'),'Low'),@('SVC-007','Xbox Services',@('XblAuthManager','XblGameSave','XboxGipSvc','XboxNetApiSvc'),'Low'),@('SVC-008','Fax',@('Fax'),'Low'),@('SVC-009','Print Spooler',@('Spooler'),'High'));foreach($check in $checks){Test-ServiceDisabled -ControlID $check[0] -Title $check[1] -Names $check[2] -Severity $check[3]}}
Export-ModuleMember -Function Invoke-Audit
<#
.SYNOPSIS
    Provides legacy Windows service-hardening checks.
.DESCRIPTION
    Retained for compatibility with framework v1. The v2 CIS entry point reads
    service requirements from versioned benchmark definitions.
#>
