Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-SmbResult { param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation) New-CISResult -ControlID $ControlID -Category 'SMB' -SubCategory 'Server Message Block' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - Network File System'
}
function Get-SmbProperty {param([object]$Object,[string]$Name)if($null -ne $Object -and $null -ne $Object.PSObject.Properties[$Name]){return $Object.$Name};return $null}
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    try{$server=Get-SmbServerConfiguration -ErrorAction Stop;$client=Get-SmbClientConfiguration -ErrorAction Stop}catch{foreach($item in @(@('SMB-001','SMBv1 Enabled'),@('SMB-002','SMB Signing'),@('SMB-003','Guest Access'),@('SMB-004','SMB Encryption'),@('SMB-005','SMB Client Settings'),@('SMB-006','SMB Server Settings'))){New-SmbResult -ControlID $item[0] -Title $item[1] -Expected 'SMB configuration is available.' -Actual 'Unavailable' -Status WARNING -Severity High -Evidence $_.Exception.Message -Remediation 'Verify SMB client and server management cmdlets are available.'};return}
    $smb1Server=Get-SmbProperty $server 'EnableSMB1Protocol';$smb1Client=Get-SmbProperty $client 'EnableSMB1Protocol';New-SmbResult -ControlID 'SMB-001' -Title 'SMBv1 Enabled' -Expected 'Disabled for SMB client and server' -Actual ('Server={0}; Client={1}' -f $smb1Server,$smb1Client) -Status $(if($smb1Server -eq $false -and $smb1Client -eq $false){'PASS'}else{'FAIL'}) -Severity Critical -Evidence ('EnableSMB1Protocol: server={0}; client={1}.' -f $smb1Server,$smb1Client) -Remediation 'Disable SMBv1 on both the SMB client and server.'
    $srvSigning=Get-SmbProperty $server 'RequireSecuritySignature';$cliSigning=Get-SmbProperty $client 'RequireSecuritySignature';New-SmbResult -ControlID 'SMB-002' -Title 'SMB Signing' -Expected 'Required for SMB client and server' -Actual ('Server={0}; Client={1}' -f $srvSigning,$cliSigning) -Status $(if($srvSigning -and $cliSigning){'PASS'}else{'FAIL'}) -Severity High -Evidence ('RequireSecuritySignature: server={0}; client={1}.' -f $srvSigning,$cliSigning) -Remediation 'Require SMB signing on both the SMB client and server.'
    $guest=Get-SmbProperty $client 'EnableInsecureGuestLogons';New-SmbResult -ControlID 'SMB-003' -Title 'Guest Access' -Expected 'Insecure guest logons disabled' -Actual ([string]$guest) -Status $(if($guest -eq $false){'PASS'}else{'FAIL'}) -Severity High -Evidence ('EnableInsecureGuestLogons: {0}.' -f $guest) -Remediation 'Disable insecure SMB guest logons.'
    $encrypt=Get-SmbProperty $server 'EncryptData';New-SmbResult -ControlID 'SMB-004' -Title 'SMB Encryption' -Expected 'Enabled where SMB shares carry sensitive data' -Actual ([string]$encrypt) -Status $(if($encrypt){'PASS'}else{'WARNING'}) -Severity Medium -Evidence ('EncryptData: {0}.' -f $encrypt) -Remediation 'Enable SMB encryption globally or on each share that handles sensitive data.'
    $clientFields=@('RequireSecuritySignature','EnableSecuritySignature','EnableInsecureGuestLogons','ConnectionCountPerRssNetworkInterface');$clientText=@($clientFields|ForEach-Object{'{0}={1}' -f $_,(Get-SmbProperty $client $_)});New-SmbResult -ControlID 'SMB-005' -Title 'SMB Client Settings' -Expected 'Client settings are reviewed and secure' -Actual ($clientText -join '; ') -Status PASS -Severity Medium -Evidence ($clientText -join '; ') -Remediation 'Review SMB client settings and require signing while disabling insecure guest access.'
    $serverFields=@('RequireSecuritySignature','EnableSecuritySignature','EnableSMB1Protocol','EncryptData');$serverText=@($serverFields|ForEach-Object{'{0}={1}' -f $_,(Get-SmbProperty $server $_)});New-SmbResult -ControlID 'SMB-006' -Title 'SMB Server Settings' -Expected 'Server settings are reviewed and secure' -Actual ($serverText -join '; ') -Status PASS -Severity Medium -Evidence ($serverText -join '; ') -Remediation 'Review SMB server settings, disable SMBv1, and require signing.'
}
Export-ModuleMember -Function Invoke-Audit
