Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Result.psm1') -Force -ErrorAction Stop
function New-TlsResult { param([string]$ControlID,[string]$Title,[string]$Expected,[string]$Actual,[ValidateSet('PASS','FAIL','WARNING','NOT APPLICABLE')][string]$Status,[ValidateSet('Critical','High','Medium','Low','Informational')][string]$Severity,[string]$Evidence,[string]$Remediation) New-CISResult -ControlID $ControlID -Category 'TLS' -SubCategory 'Schannel' -Title $Title -Expected $Expected -Actual $Actual -Status $Status -Severity $Severity -Evidence $Evidence -Remediation $Remediation -Reference 'CIS Microsoft Windows 10/11 Benchmark - Cryptography'
}
function Get-SchChannelProtocol {param([string]$Name)[string[]]$roles='Client','Server';$values=@();foreach($role in $roles){$path="HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\$Name\$role";try{$p=Get-ItemProperty -LiteralPath $path -ErrorAction Stop;$values+=[pscustomobject]@{Role=$role;Exists=$true;Enabled=$p.Enabled;DisabledByDefault=$p.DisabledByDefault}}catch{$values+=[pscustomobject]@{Role=$role;Exists=$false;Enabled=$null;DisabledByDefault=$null}}};return $values}
function Invoke-Audit {
    [CmdletBinding()][OutputType([System.Management.Automation.PSCustomObject])]param()
    $protocols=@(@('TLS-001','SSL 2.0',$false),@('TLS-002','SSL 3.0',$false),@('TLS-003','TLS 1.0',$false),@('TLS-004','TLS 1.1',$false),@('TLS-005','TLS 1.2',$true),@('TLS-006','TLS 1.3',$true))
    foreach($spec in $protocols){$items=@(Get-SchChannelProtocol $spec[1]);$actual=@($items|ForEach-Object{'{0}: Enabled={1}, DisabledByDefault={2}' -f $_.Role,$_.Enabled,$_.DisabledByDefault});if(@($items|Where-Object{-not $_.Exists}).Count -gt 0){$status='WARNING'}elseif($spec[2]){$status=if(@($items|Where-Object{$_.Enabled -ne 1 -or $_.DisabledByDefault -ne 0}).Count -eq 0){'PASS'}else{'FAIL'}}else{$status=if(@($items|Where-Object{$_.Enabled -ne 0 -or $_.DisabledByDefault -ne 1}).Count -eq 0){'PASS'}else{'FAIL'}};New-TlsResult -ControlID $spec[0] -Title $spec[1] -Expected $(if($spec[2]){'Enabled for client and server'}else{'Disabled for client and server'}) -Actual ($actual -join '; ') -Status $status -Severity $(if($spec[2]){'Medium'}else{'High'}) -Evidence ('SCHANNEL protocol values: {0}.' -f ($actual -join '; ')) -Remediation $(if($spec[2]){"Explicitly enable $($spec[1]) for client and server Schannel."}else{"Explicitly disable $($spec[1]) for client and server Schannel."})}
    try{$cipherSuites=@(Get-TlsCipherSuite -ErrorAction Stop|Select-Object -ExpandProperty Name);$suiteStatus=if($cipherSuites.Count){'PASS'}else{'FAIL'};$suiteActual=($cipherSuites -join '; ');$suiteEvidence=('Enabled cipher suite count: {0}.' -f $cipherSuites.Count)}catch{$cipherSuites=@();$suiteStatus='WARNING';$suiteActual='Unavailable';$suiteEvidence=$_.Exception.Message};New-TlsResult -ControlID 'TLS-007' -Title 'Cipher Suites' -Expected 'Cipher suites are available for review' -Actual $suiteActual -Status $suiteStatus -Severity Medium -Evidence $suiteEvidence -Remediation 'Configure a modern cipher-suite order using supported TLS policy.'
    if($suiteStatus -eq 'WARNING'){New-TlsResult -ControlID 'TLS-008' -Title 'Weak Cipher Suites' -Expected 'No weak cipher suites are enabled' -Actual 'Unavailable' -Status WARNING -Severity High -Evidence $suiteEvidence -Remediation 'Review cipher suites and remove weak algorithms.'}else{$weak=@($cipherSuites|Where-Object{$_ -match '(?i)(RC4|3DES|(^|_)DES_|NULL|EXPORT|MD5|TLS_RSA_)'});New-TlsResult -ControlID 'TLS-008' -Title 'Weak Cipher Suites' -Expected 'No RC4, DES, 3DES, NULL, EXPORT, MD5, or static-RSA cipher suites' -Actual $(if($weak.Count){$weak -join '; '}else{'None found'}) -Status $(if($weak.Count){'FAIL'}else{'PASS'}) -Severity High -Evidence ('Weak cipher suite count: {0}.' -f $weak.Count) -Remediation 'Remove weak cipher suites and prioritize modern ECDHE AES-GCM or ChaCha20 suites.'}
}
Export-ModuleMember -Function Invoke-Audit
