Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'SecurityAuditUtilities.psm1') -Force -ErrorAction Stop
function Invoke-Audit {[CmdletBinding()][OutputType([pscustomobject])]param();try{$svc=Get-Service wuauserv -ErrorAction Stop;$a=$svc.Status.ToString();$st=if($svc.Status -eq 'Running'){'PASS'}else{'FAIL'};New-CISAuditFinding 'WU-001' 'Windows Update' 'Update Service' 'Windows Update Service' 'Running' $a $st High "wuauserv=$a" 'Start and configure the Windows Update service.'}catch{New-CISAuditFinding 'WU-001' 'Windows Update' 'Update Service' 'Windows Update Service' 'Available' 'Unavailable' WARNING High $_.Exception.Message 'Verify Windows Update service availability.'};$p='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate';$au="$p\AU";foreach($i in @(@('WU-002','Automatic Updates',$au,'NoAutoUpdate'),@('WU-003','WSUS Configuration',$p,'WUServer'),@('WU-007','Update Pause',$p,'PauseFeatureUpdatesStartTime'))){$v=Get-CISRegistryValue $i[2] $i[3];New-CISAuditFinding $i[0] 'Windows Update' 'Update Policy' $i[1] 'Policy is configured and reviewed.' ([string]$v) $(if($null -eq $v){'WARNING'}else{'PASS'}) Medium ("$($i[3])=$v") 'Review and configure Windows Update policy.'};$reboot=Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired';New-CISAuditFinding 'WU-006' 'Windows Update' 'Update State' 'Reboot Required' 'No update reboot is pending.' ([string]$reboot) $(if($reboot){'FAIL'}else{'PASS'}) Medium "RebootRequired=$reboot" 'Restart the device to complete pending updates.';foreach($i in @(@('WU-004','Last Successful Update'),@('WU-005','Pending Updates'))){New-CISAuditFinding $i[0] 'Windows Update' 'Update State' $i[1] 'Update state is reviewed.' 'Use Windows Update history/API for current state.' WARNING Low 'Native Windows Update history varies by servicing stack.' 'Review update history and pending updates through Windows Update management.'};New-CISAuditFinding 'WU-008' 'Windows Update' 'Update State' 'Missing Critical Updates' 'No critical updates are missing.' 'Requires update scan.' WARNING High 'A read-only online update scan is not initiated by this module.' 'Review critical update compliance in Windows Update or centralized management.'}
Export-ModuleMember -Function Invoke-Audit
<#
.SYNOPSIS
    Provides legacy Windows Update advisory checks.
.DESCRIPTION
    Retained for compatibility with framework v1. The v2 CIS entry point reads
    update-policy requirements from the selected benchmark definition.
#>
